export enum SCREENS {
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  HOME_SCREEN = 'HOME_SCREEN',
  ACTIVATE_VOTING_POLL_SCREEN = 'ACTIVATE_VOTING_POLL_SCREEN',
  CREATE_SESSION_SCREEN = 'CREATE_SESSION_SCREEN',
  EDIT_SESSION_SCREEN = 'EDIT_SESSION_SCREEN',
  SESSION_DETAILS_SCREEN = 'SESSION_DETAILS_SCREEN',
  SESSION_ONBOARDING_SCREEN = 'SESSION_ONBOARDING_SCREEN',
  VOTE_FOR_CONTESTENT_SCREEN = 'VOTE_FOR_CONTESTENT_SCREEN',
  APP_NAVIGATOR = 'APP_NAVIGATOR',
}

export enum APP_ROLES {
  ADMIN = 'ADMIN',
  VOTER = 'VOTER',
}
