export enum SCREENS {
  // screen names
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  SIGNUP_SCREEN = 'SIGNUP_SCREEN',
  HOME_SCREEN = 'HOME_SCREEN',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  ALL_VOTING_POLLS_SCREEN = 'ALL_VOTING_POLLS_SCREEN',
  CAST_VOTE_SCREEN = 'CAST_VOTE_SCREEN',
  VOTING_POLL_RESULT_SCREEN = 'VOTING_POLL_RESULT_SCREEN',
  LEADER_BOARD_SCREEN = 'LEADER_BOARD_SCREEN',
  // Navigator
  BOTTOM_TABS = 'BOTTOM_TABS',
}
